apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: example
bases:
  - ../../application

patches:
  - path: replica_count.yaml
    target:
      kind: Deployment
      name: example-deploy
  - path: resource_limits.yaml
    target:
      kind: Deployment
      name: example-deploy
configMapGenerator:
- name: example-config
  namespace: example
  #behavior: replace
  files:
    - configs/config.json
patchesStrategicMerge:
  - env.yaml
images:
- name: aimvector/python
  newTag: 1.0.1